#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MPI MIDAS code
#----------------------------------------------------
#SBATCH -J MIDAS_mpi     # Job name
#SBATCH -o MIDAS_mpi.e%j   # Name of stdout output file
#SBATCH -e MIDAS_mpi.e%j   # Name of stdout output file
#SBATCH -p compute         # Queue name
#SBATCH -N 1               # Total number of nodes requested (64 CPUs/node)
#SBATCH -n 8               # Total number of mpi tasks requested
#SBATCH --mem=450G         # Memory (RAM) per node
#SBATCH -t 06:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-type=all     # Send email at begin and end of job
#SBATCH --mail-user="your_email"

# Set your executable directory
export RUN_DIR="$PWD"

# run application
cd $RUN_DIR
time mpirun -np 8 ./midas>Sim_MIDAS_p0004
