#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MY MPI NESCoP code
#----------------------------------------------------
#SBATCH -A JPL-PUB       # Project name
#SBATCH -J job_MIDAS     # Job name
#SBATCH -o mpi_job.e%j   # Name of stdout output file
#SBATCH -e mpi_job.e%j   # Name of stdout output file
#SBATCH -p skx-normal    # Queue name
#SBATCH -N 10             # Total number of nodes requested
#SBATCH -n 240           # Total number of mpi tasks requested
#SBATCH -t 1:30:00      # Run time (hh:mm:ss) 

# Slurm email notifications are now working
#SBATCH --mail-user=ines.fenni@gmail.com
#SBATCH --mail-type=begin   # email me when the job starts
#SBATCH --mail-type=end     # email me when the job finishes

# Launch the MPI application using ibrun
module load remora/1.8.2 
time remora ibrun ./midas>Sim_NESCoP_MPI_09-03-2020_15h46

#Note:  ibrun does not bind tasks or threads by default
#       To bind task/threads to sockets or cores, you must use
#       ibrun with tacc_affinity or use the "srun" command directly
#       with the "--cpu_bind" option.