#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MY MPI MIDAS code
#----------------------------------------------------
#SBATCH -A JPL-PUB       # Project name
#SBATCH -J job_MIDAS     # Job name
#SBATCH -o mpi_job.e%j   # Name of stdout output file
#SBATCH -e mpi_job.e%j   # Name of stdout output file
#SBATCH -p development   # Queue name
#SBATCH -N 4             # Total number of nodes requested
#SBATCH -n 192           # Total number of mpi tasks requested
#SBATCH -t 02:00:00      # Run time (hh:mm:ss) 

# Slurm email notifications are now working on Lonestar 6 
#SBATCH --mail-user=ines.fenni@gmail.com
#SBATCH --mail-type=begin   # email me when the job starts
#SBATCH --mail-type=end     # email me when the job finishes

# Launch the MPI application using ibrun
module load remora/1.8.5 
time remora ibrun ./midas>Sim_MPI_MIDAS_02-02-2024_14h15

#Note:  ibrun does not bind tasks or threads by default
#       To bind task/threads to sockets or cores, you must use
#       ibrun with tacc_affinity or use the "srun" command directly
#       with the "--cpu_bind" option.
