function plot_MIDAS_Qid_fromSimPath(Simfldr_path,Q_to_display,figs_path,plot_cells)

    % this function is to display the Qids for a NESCoP simulation from the Qid file path 
    % plots Qid (2D and 3D) from Qidtable type file with the geometry for the 3D representation 
    % can be used inside another matlab function to compare Qids
    
    % QidFilepath   : path to the the simulation folder
    % Q_to_display  : 'ext', 'sca' or 'bks'
    % shading_opt   : flat, faceted or interp; the default value is flat (if not equal to one of the three)
    % figs_path     : where the user want the figures generated by this function to be saved. put simply to '' 
    % if you want the figures to be saved in the matlab current folder
    
    % first : if we dont find a non-empty Q_files in this siumation folder
    % there is nothing to display and we exit the function 
    use_quantile = 0;
    logscale = 0;
    
    sep = '\';
    lst_Qid = dir([Simfldr_path,sep,'Q_files',sep,'*_CBFM-E.dat']) ; %
    Nfreqs = length(lst_Qid);
    if (Nfreqs == 0) 
        disp('This sim folder does not have a Q_files folder. There is nothing to display!');
        return;
    end
    for ii=1:Nfreqs
        QidFilename_split = strsplit('_',lst_Qid(ii).name,'omit');
        if (Nfreqs>1)
            freq_str = char(QidFilename_split(3));
        else
            freq_str = char(QidFilename_split(2));
        end
        lf = length(freq_str);
        f_order= freq_str(lf-2:lf);
        freqs_str(ii,:) = freq_str(1:lf-3);
        freqs(ii) = str2double(freqs_str(ii,:));
    end
    
    % num_Q in Qid files. For avg Q add 1 (num_Q+1)
    if (strcmp(Q_to_display,'ext'))
        num_Q=3;
    elseif (strcmp(Q_to_display,'sca'))
        num_Q=5;
    elseif (strcmp(Q_to_display,'bks'))
        num_Q=6;
    else
        disp('Unknown Qtype !!')
        exit;
    end
    
    % SimFullName
    SimFolderPath_split = strsplit(sep,Simfldr_path,'omit');
    L = char(SimFolderPath_split); l =size(L,1);
    SimFullName = char(SimFolderPath_split(l));
    
    %NIconfig 
    IncScatfile_path = [Simfldr_path,sep,'IncScattDirs.dat'];
    fid0 = fopen(IncScatfile_path);
    if (fid0 > 0)
        tline = fgetl(fid0);tline = fgetl(fid0);
        tline_splt=strsplit(' ',tline,'omit');
        Ninc_str = strtrim(char(tline_splt(3)));
        tline = fgetl(fid0);
        tline_splt=strsplit('=',tline,'omit');
        NItype = strtrim(char(tline_splt(2)));
        NIconfig = [NItype,Ninc_str];
    else
        disp('Error !! : Enable to read NIconfig');
        return;
    end
    fclose(fid0);
    % Qavg
    Qfile_path = [Simfldr_path,sep,'qtable_CBFM-E.dat'];
    fid1 = fopen(Qfile_path);
    tline = fgetl(fid0);
    tline_splt=strsplit('=',tline,'omit');
    Nbc = str2double(char(tline_splt(2)));
    if (fid1 > 0)
        if (strcmp(NItype,'aq'))
            C1 = textscan(fid1,'%f %f %f %f %f %f %f %f %d','headerLines',8);
        else
            C1 = textscan(fid1,'%f %f %f %f %f %f %f %f %d','headerLines',4);
        end
        Qavg = C1{num_Q+1}; 
    else
        disp('Error !! : Enable to read Qavg');
        return;
    end
    fclose(fid1); 
    % CellsFilepath 
    CellsFilepath = [Simfldr_path,sep,'Cells.dat'];
    fid0 = fopen(CellsFilepath);
    if (fid0 > 0) 
        C0 = textscan(fid0,'%f %f %f %f %d %d' ,'headerLines',0);
        X = C0{1};Y = C0{2};Z = C0{3};
        fclose(fid0);
    else
        disp('Error !! : Enable to read Cells.dat file ');
        fclose(fid0);
        return;
    end
        
    
    %% *********************************************************************************
    %*********************************************************************************
    % PLOT 2D Q       **************************************************************
    %*********************************************************************************
    if (isempty(figs_path))
        figs_path = SimFullName; 
        if (~exist(SimFullName,'dir'))
            mkdir(SimFullName);
        end
    end
    
    % plot geometry 
    if (plot_cells == 1)
        figure();  set(gcf,'Position',[150 100 800 800]); 
        plot3(1e3*X,1e3*Y,1e3*Z,'.');
        xlabel('X (mm)'); ylabel('Y (mm)'); zlabel('Z (mm)');
        grid on; axis equal;title('geometry from Cells.dat file')
        saveas(gcf,[figs_path,sep,'cells.fig'],'fig');    
        saveas(gcf,[figs_path,sep,'cells.png'],'png');
    end
    
    
    for ii=1:Nfreqs
        %if (ii==3); Qid_min = Qid_min_nes; Qid_max = Qid_max_nes; end
        QidFilepath = [Simfldr_path,sep,'Q_files',sep,char(lst_Qid(ii).name)];
        freq_sim = freqs_str(ii,:);
        
        %% plot & save 2D figures   
        fid0 = fopen(QidFilepath);
        C1 = textscan(fid0,'%f %f %f %f %f %f %f','headerLines',1);
        Nid = size(C1{1},1);
    
        th(1:Nid) = C1{1};
        ph(1:Nid) = C1{2};
    
        Qid(1:Nid)=C1{num_Q}; 
        fclose(fid0);  
        % 2D
        figure;
        sz = 80; scatter(th,ph,sz,Qid,'filled'); 
        title(['Q_{',Q_to_display,'} with ',NIconfig,'id @ f = ',freq_sim,' ',f_order]);
        xlim([0 180]); ylim([0 360]);
        colorbar; if (exist('Qid_min','var')), caxis([Qid_min Qid_max]);end
        xlabel('\theta_i');ylabel('\phi_i');
        colormap(jet(20));set(gca,'FontSize',20);set(gcf,'Position',[470 100 600 600]);
        if (logscale == 1) 
            set(gca,'ColorScale','log');
        end
        if (use_quantile ==1) 
            c_lim = [quantile(Qid(~isnan(Qid)),0.01),...
                       quantile(Qid(~isnan(Qid)),0.99)] ; 
            caxis(c_lim);
        end
        
        saveas(gcf,[figs_path,sep,'Q',Q_to_display,'_',freq_sim,'GHz_2D_',NIconfig,'id.fig'],'fig');
        saveas(gcf,[figs_path,sep,'Q',Q_to_display,'_',freq_sim,'GHz_2D_',NIconfig,'id.png'],'png');
        
        % plot Qid histogram 
        figure; hist(Qid,100);grid;
        xlabel('Q_{id}');ylabel('#');
        annotation('textbox',[.7 .08 .2 .8],'String',['Q_{min}= ',num2str(min(Qid))],'FitBoxToText','on',...
            'LineStyle', 'none','FontWeight','bold','color','k','FontSize',14);
        annotation('textbox',[.7 .03 .2 .8],'String',['Q_{max}= ',num2str(max(Qid))],'FitBoxToText','on',...
            'LineStyle', 'none','FontWeight','bold','color','k','FontSize',14);
        set(gca,'FontSize',18);
        title(['Q_{',Q_to_display,'} with ',NIconfig,'id @ f = ',freq_sim,' ',f_order]);
        set(gcf,'Position',[150 100 1200 500]);
        saveas(gcf,[figs_path,sep,'Q',Q_to_display,'_',freq_sim,'GHz_hist_',NIconfig,'id.png'],'png');
        saveas(gcf,[figs_path,sep,'Q',Q_to_display,'_',freq_sim,'GHz_hist_',NIconfig,'id.fig'],'fig');
    end
end